# Specify a different separator for branch names

version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
  - package-ecosystem: "pip"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"

registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    username: bufkes
    password: ${{secrets.NPM_TOKEN}}  # Must be an unencoded password
