name: "Github Security Sync Test"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '*/10 * * * *'    # trigger synchronization every 10 minutes

# jobs:
#   test_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Sync alerts to Jira issues
#         uses: github/ghas-jira-integration@v1
#         with:
#           jira_url: 'https://redoxengine.atlassian.net/'
#           jira_user: '${{ secrets.JIRA_USER }}'
#           jira_token: '${{ secrets.JIRA_TOKEN }}'
#           jira_project: 'SEC'
#           sync_direction: 'jira2gh'
          
#  name: GitHub Security Alerts for Jira

# on:
#   schedule:
#     - cron: '0 */6 * * *'

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.x
        env:
          GH_SECURITY_TOKEN: '${{ secrets.GH_TOKEN }}'
          JIRA_TOKEN: '${{ secrets.JIRA_TOKEN }}'
          JIRA_HOST: 'https://redoxengine.atlassian.net'
          JIRA_USER: '${{ secrets.JIRA_USER }}'
          JIRA_PROJECT: 'SEC'
          JIRA_ISSUE_TYPE: 'Bug'
          JIRA_WATCHERS: bufkes@redoxengine.com
